version: '3'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MC_VERSION: 1.18.1  # Define la versión aquí también si usas Docker Compose
    ports:
      - "25565:25565"
    volumes:
      - ./data:/minecraft
    environment:
      EULA: "true"
    restart: unless-stopped
