version: '3'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - ./data:/minecraft
    environment:
      EULA: "true"
    restart: unless-stopped
